# Generated by Django 4.1.7 on 2023-03-08 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_gen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='name',
            field=models.TextField(max_length=50, unique=True),
        ),
    ]
