# Generated by Django 4.1.7 on 2023-03-08 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csv_gen', '0003_schemas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewUser',
            new_name='User',
        ),
    ]
