# Generated by Django 4.1.7 on 2023-03-08 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_gen', '0004_rename_newuser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemas',
            name='modified',
            field=models.DateField(null=True),
        ),
    ]
