# Generated by Django 4.1.7 on 2023-03-08 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_gen', '0005_schemas_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemas',
            name='modified',
            field=models.DateField(),
        ),
    ]
