# Generated by Django 4.1.7 on 2023-03-08 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csv_gen', '0006_alter_schemas_modified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schemas',
            old_name='fle_name',
            new_name='file_name',
        ),
    ]
