# Generated by Django 4.1.7 on 2023-03-08 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csv_gen', '0008_rename_schemas_schema'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schema',
            name='file_name',
        ),
    ]
